---
version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - '5433:5432'
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - ./.pgpass:/root/.pgpass
